Revert "update maven plugin property syntax"
This reverts commit abc228a3dc9b8d8db628678af6f0af00f2618d67.

(there seems to be a problem with the deployments mojo running in Cru's jenkins instance:
  org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter, adder nor field in org.ccci.deployment.maven.DeployMojo for 'deployments.promptPassword'
    at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.<init>(ComponentValueSetter.java:95)
I'm not sure what's going on, but it might be related to this commit.)